"""
보드 구현 전반에 사용되는 상수 모음.
"""

# Post Activities
ACTIVITY_VIEW = 'VIEW'
ACTIVITY_VOTE = 'VOTE'

# 보드 역할
BOARD_ROLE_DEFAULT = 0
BOARD_ROLE_PROJECT = 1
BOARD_ROLE_DEBATE = 11

# 사업 진행상황
PROJECT_STATUS_ALWAYS = 0
PROJECT_STATUS_DONE = 1
PROJECT_STATUS_QUIT = 2
PROJECT_STATUS_ONGOING = 3

# 배너 캐러셀 노출위치
BANNER_CAROUSEL_SECTOR_MAIN = 0