# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-24 10:02
from __future__ import unicode_literals

import apps.board.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.board.models.get_upload_path, verbose_name='첨부파일')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일(들)',
            },
        ),
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('content_ko', models.TextField(null=True, verbose_name='내용')),
                ('content_en', models.TextField(null=True, verbose_name='내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제글')),
                ('is_secret', models.BooleanField(default=False, verbose_name='비밀글')),
                ('vote_up', models.IntegerField(default=0, verbose_name='추천수')),
                ('vote_down', models.IntegerField(default=0, verbose_name='비추천수')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.Service')),
                ('is_main', models.BooleanField(default=False, verbose_name='메인페이지 노출')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판(들)',
            },
            bases=('manager.service',),
        ),
        migrations.CreateModel(
            name='PostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40, verbose_name='IP 주소')),
                ('activity', models.CharField(choices=[('VIEW', '조회'), ('VOTE', '추천/비추천')], max_length=4, verbose_name='활동구분')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='태그명')),
                ('name_ko', models.CharField(max_length=32, null=True, unique=True, verbose_name='태그명')),
                ('name_en', models.CharField(max_length=32, null=True, unique=True, verbose_name='태그명')),
                ('abbr', models.CharField(help_text='긴 태그명의 경우 태그명 대신 표시할 짧은 축약어입니다.', max_length=16, unique=True, verbose_name='태그 축약어')),
                ('abbr_ko', models.CharField(help_text='긴 태그명의 경우 태그명 대신 표시할 짧은 축약어입니다.', max_length=16, null=True, unique=True, verbose_name='태그 축약어')),
                ('abbr_en', models.CharField(help_text='긴 태그명의 경우 태그명 대신 표시할 짧은 축약어입니다.', max_length=16, null=True, unique=True, verbose_name='태그 축약어')),
                ('slug', models.CharField(help_text='URL 상 태그를 구분짓는 짧은 지시자입니다.', max_length=8, unique=True, verbose_name='태그 슬러그')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='게시판')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그(들)',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.BasePost')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글(들)',
                'ordering': ['date'],
            },
            bases=('board.basepost',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.BasePost')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('title_ko', models.CharField(max_length=128, null=True, verbose_name='제목')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='제목')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지글')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='등록 게시판')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Tag', verbose_name='태그')),
            ],
            options={
                'verbose_name': '포스트',
                'verbose_name_plural': '포스트(들)',
            },
            bases=('board.basepost',),
        ),
        migrations.AddField(
            model_name='postactivity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BasePost', verbose_name='포스트'),
        ),
        migrations.AddField(
            model_name='postactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AddField(
            model_name='basepost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='basepost',
            name='involved_users',
            field=models.ManyToManyField(related_name='involved_posts', through='board.PostActivity', to=settings.AUTH_USER_MODEL, verbose_name='참여자'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BasePost', verbose_name='연결된 포스트'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Post', verbose_name='상위 포스트'),
        ),
    ]
