# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTab',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.Service')),
                ('parent_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='탭이 속한 게시판')),
            ],
            options={
                'verbose_name': '탭',
                'verbose_name_plural': '탭(들)',
                'ordering': ['parent_board', 'level'],
            },
            bases=('manager.service',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.BasePost')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='기구명')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='전화번호')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='소통창구 링크')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='등록 게시판')),
                ('board_tab', models.ManyToManyField(blank=True, to='board.BoardTab', verbose_name='등록 탭')),
            ],
            options={
                'verbose_name': '연락망',
                'verbose_name_plural': '연락망(들)',
            },
            bases=('board.basepost',),
        ),
        migrations.CreateModel(
            name='DebatePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Post')),
                ('is_closed', models.BooleanField(default=False, verbose_name='논쟁 종결 여부')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='종결 예정일')),
            ],
            bases=('board.post',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('description', models.TextField(verbose_name='상품 설명')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='등록 게시판')),
                ('board_tab', models.ManyToManyField(blank=True, to='board.BoardTab', verbose_name='등록 탭')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품(들)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Post')),
                ('status', models.IntegerField(choices=[('ALWAYS', 0), ('DONE', 1), ('QUIT', 2), ('ONGOING', 3)], default='ALWAYS', verbose_name='프로젝트 진행 상태')),
                ('is_pledge', models.BooleanField(default=False, verbose_name='공약 여부')),
                ('alteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BasePost', verbose_name='프로젝트 일정')),
            ],
            bases=('board.post',),
        ),
        migrations.CreateModel(
            name='WebDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_url', models.TextField(blank=True, verbose_name='웹 문서 삽입 URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BasePost', verbose_name='연결된 포스트')),
            ],
            options={
                'verbose_name': '웹문서 링크',
                'verbose_name_plural': '웹문서 링크(들)',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ProductCategory', verbose_name='상품 카테고리'),
        ),
        migrations.AddField(
            model_name='post',
            name='board_tab',
            field=models.ManyToManyField(blank=True, to='board.BoardTab', verbose_name='등록 탭'),
        ),
    ]

