# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180210_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('date', models.DateTimeField(verbose_name='날짜')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='alteration',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='status',
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='is_pledge',
            field=models.BooleanField(default=False, verbose_name='공약'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ProjectPost', verbose_name='게시글'),
        ),
    ]
