# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180208_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.BasePost')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('title_ko', models.CharField(max_length=128, null=True, verbose_name='제목')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='제목')),
                ('url', models.URLField(null=True, verbose_name='링크 URL')),
                ('image', models.ImageField(upload_to='banner', verbose_name='이미지')),
            ],
            options={
                'verbose_name_plural': '배너(들)',
                'verbose_name': '배너',
            },
            bases=('board.basepost',),
        ),
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.IntegerField(choices=[(0, '메인페이지')], verbose_name='노출위치')),
                ('banners', models.ManyToManyField(to='board.Banner', verbose_name='배너')),
            ],
            options={
                'verbose_name_plural': '배너그룹(들)',
                'verbose_name': '배너그룹',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.BasePost')),
                ('url', models.URLField(verbose_name='URL')),
                ('text', models.CharField(max_length=128, verbose_name='텍스트')),
                ('text_ko', models.CharField(max_length=128, null=True, verbose_name='텍스트')),
                ('text_en', models.CharField(max_length=128, null=True, verbose_name='텍스트')),
            ],
            options={
                'verbose_name_plural': '링크(들)',
                'verbose_name': '링크',
            },
            bases=('board.basepost',),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='status',
            field=models.IntegerField(choices=[(0, '항상'), (1, '완료'), (2, '파기'), (3, '진행중')], default=0, verbose_name='프로젝트 진행 상태'),
        ),
    ]
