# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20180216_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={'verbose_name': '사업', 'verbose_name_plural': '사업(들)'},
        ),
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.CharField(choices=[('DEFAULT', '기본'), ('PROJECT', '사업'), ('PLANBOOK', '정책자료집'), ('DEBATE', '논의')], default='DEFAULT', max_length=32, verbose_name='보드 역할'),
        ),
    ]
