# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180214_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={'verbose_name': '사업 포스트', 'verbose_name_plural': '사업 포스트(들)'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='title_en',
            field=models.CharField(max_length=128, null=True, verbose_name='일정'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='title_ko',
            field=models.CharField(max_length=128, null=True, verbose_name='일정'),
        ),
        migrations.AlterField(
            model_name='boardtab',
            name='url',
            field=models.CharField(help_text="탭을 나타낼 하위 경로만 적어주세요('/'를 포함하면 안됩니다)", max_length=32, verbose_name='하위 주소'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=128, verbose_name='일정'),
        ),
    ]
