# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180217_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글(들)'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '상품 카테고리', 'verbose_name_plural': '상품 카테고리(들)'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='카테고리명'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ko',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='카테고리명'),
        ),
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.CharField(choices=[('DEFAULT', '기본'), ('PROJECT', '사업'), ('PLANBOOK', '정책자료집'), ('DEBATE', '논의'), ('ARCHIVING', '아카이빙'), ('WORKHOUR', '상근관리'), ('STORE', '상점')], default='DEFAULT', max_length=32, verbose_name='보드 역할'),
        ),
        migrations.AlterField(
            model_name='product',
            name='board_tab',
            field=models.ManyToManyField(blank=True, null=True, to='board.BoardTab', verbose_name='등록 탭'),
        ),
        migrations.AlterField(
            model_name='product',
            name='board_tab',
            field=models.ManyToManyField(to='board.BoardTab', verbose_name='등록 탭'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상품 설명'),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': '상품', 'verbose_name_plural': '상품(들)'},
        ),
    ]
