# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180210_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='role',
            field=models.IntegerField(choices=[(0, '기본'), (1, '사업')], default=0, verbose_name='보드 역할'),
        ),
    ]
