# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20180218_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='기구명'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ko',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='기구명'),
        ),
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.CharField(choices=[('DEFAULT', '기본'), ('PROJECT', '사업'), ('PLANBOOK', '정책자료집'), ('DEBATE', '논의'), ('ARCHIVING', '아카이빙'), ('WORKHOUR', '상근관리'), ('SWIPER', '격주보고'), ('STORE', '상점'), ('CONTACT', '산하기구')], default='DEFAULT', max_length=32, verbose_name='보드 역할'),
        ),
    ]
