# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('board', '0004_auto_20180218_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardBanner',
            fields=[
                ('topbanner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.TopBanner')),
            ],
            options={
                'verbose_name': '보드배너',
                'verbose_name_plural': '보드배너(들)',
            },
            bases=('manager.topbanner',),
        ),
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.CharField(choices=[('DEFAULT', '기본'), ('PROJECT', '사업'), ('PLANBOOK', '정책자료집'), ('DEBATE', '논의'), ('ARCHIVING', '아카이빙'), ('WORKHOUR', '상근관리'), ('SPONSOR', '제휴리스트'), ('SWIPER', '격주보고'), ('STORE', '상점')], default='DEFAULT', max_length=32, verbose_name='보드 역할'),
        ),
        migrations.AddField(
            model_name='boardbanner',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board', verbose_name='등록 게시판'),
        ),
        migrations.AddField(
            model_name='boardbanner',
            name='board_tab',
            field=models.ManyToManyField(blank=True, to='board.BoardTab', verbose_name='등록 탭'),
        ),
    ]
