# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='role',
            field=models.IntegerField(choices=[(0, '기본'), (1, '사업'), (11, '논의')], default=0, verbose_name='보드 역할'),
        ),
    ]
