# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-13 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_merge_20180310_2200'),
        ('board', '0007_auto_20180311_1704'),
    ]

    operations = [
    ]
