# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.CharField(default='/', help_text='도메인 하위 경로만 적어주세요. /aaa/bbb 형식을 지켜주세요. 특정 페이지에 리다이렉팅 할 서비스의 경우 https://www.google.com/ 형식을 해주시면 됩니다.', max_length=100, verbose_name='최상위 주소'),
        ),
    ]
