# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='텍스트')),
                ('url', models.URLField(null=True, verbose_name='링크 URL')),
                ('terminate_at', models.DateTimeField(help_text='공란일경우, 직접 삭제시까지 노출됩니다', null=True, verbose_name='노출종료일시')),
            ],
            options={
                'verbose_name_plural': '탑배너(들)',
                'verbose_name': '탑배너',
            },
        ),
    ]
