# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_topbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='text_en',
            field=models.CharField(max_length=128, null=True, verbose_name='텍스트'),
        ),
        migrations.AddField(
            model_name='topbanner',
            name='text_ko',
            field=models.CharField(max_length=128, null=True, verbose_name='텍스트'),
        ),
    ]
