# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-15 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='portal_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저 인스턴스')),
                ('kaist_uid', models.CharField(max_length=128, unique=True, verbose_name='KAIST UID')),
                ('ku_kname', models.CharField(blank=True, max_length=128, verbose_name='이름')),
                ('ku_acad_prog', models.CharField(blank=True, max_length=32, verbose_name='과정')),
                ('ku_std_no', models.CharField(blank=True, max_length=32, verbose_name='학번')),
                ('ku_psft_user_status_kor', models.CharField(blank=True, max_length=32, verbose_name='학적상태')),
                ('ku_born_date', models.CharField(blank=True, max_length=32, verbose_name='생년월일')),
                ('ku_sex', models.CharField(blank=True, max_length=32, verbose_name='성별')),
                ('ou', models.CharField(blank=True, max_length=32, verbose_name='학과')),
                ('mail', models.CharField(blank=True, max_length=32, verbose_name='메일주소')),
                ('mobile', models.CharField(blank=True, max_length=32, verbose_name='전화번호')),
                ('is_signed_up', models.BooleanField(default=False, help_text='정보제공에 반대하면 계정삭제 처리가 되나, 아직 동의여부를 선택하지 않은 최초가입자의 경우 의사표현 시까지 정보가 임시저장됩니다. 이 특수경우에는 정보를 활용하지 않아야 합니다.', verbose_name='정보제공 동의여부')),
            ],
        ),
    ]
