# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-15 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('pages', models.TextField()),
                ('intro', models.TextField()),
                ('ad', models.TextField()),
                ('is_band', models.BooleanField(default=False)),
                ('video_url1', models.CharField(max_length=63)),
                ('video_url2', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Freshman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsize', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freshman', to=settings.AUTH_USER_MODEL)),
                ('voted_clubs', models.ManyToManyField(related_name='votes', to='ot.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='ot/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ot.Club')),
            ],
        ),
        migrations.CreateModel(
            name='VotePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test', models.BooleanField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
