# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-01-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': '동아리 정보', 'verbose_name_plural': '동아리 정보(들)'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '동아리 홍보 사진', 'verbose_name_plural': '동아리 홍보 사진(들)'},
        ),
        migrations.RemoveField(
            model_name='club',
            name='ad',
        ),
        migrations.AddField(
            model_name='club',
            name='one_line_intro',
            field=models.TextField(blank=True, verbose_name='동아리 한 줄 소개(메인 화면)'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='메인 화면에 올라갈 사진인가 (하나만 가능)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='intro',
            field=models.TextField(verbose_name='동아리 소개'),
        ),
        migrations.AlterField(
            model_name='club',
            name='is_band',
            field=models.BooleanField(default=False, verbose_name='밴드 여부'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=63, verbose_name='동아리 이름'),
        ),
        migrations.AlterField(
            model_name='club',
            name='pages',
            field=models.TextField(blank=True, verbose_name='동아리 페이스북/유튜브 페이지 주소'),
        ),
        migrations.AlterField(
            model_name='club',
            name='video_url1',
            field=models.CharField(blank=True, max_length=63, verbose_name='동아리 소개 비디오 주소 #1'),
        ),
        migrations.AlterField(
            model_name='club',
            name='video_url2',
            field=models.CharField(blank=True, max_length=63, verbose_name='동아리 소개 비디오 주소 #2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ot.Club', verbose_name='동아리'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='ot/', verbose_name='홍보 사진'),
        ),
    ]
