# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('CHAP', '장'), ('PRE', '전문'), ('SUPPL', '부칙'), ('SEC', '절')], max_length=8, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('CONST', '회칙'), ('ETC', '기타규정'), ('BYLAW', '세칙'), ('RULE', '규칙')], max_length=8, verbose_name='종류'),
        ),
    ]
