# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_auto_20180210_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('CHAP', '장'), ('SEC', '절'), ('PRE', '전문'), ('SUPPL', '부칙')], max_length=8, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='revision_type',
            field=models.CharField(choices=[('FULL', '전부개정'), ('PART', '일부개정'), ('ESTAB', '제정')], max_length=8, verbose_name='제개정 종류'),
        ),
    ]
