# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-27 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0004_auto_20180217_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_type',
            field=models.CharField(choices=[('PRE', '전문'), ('CHAP', '장'), ('SEC', '절'), ('SUPPL', '부칙')], max_length=8, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('CONST', '회칙'), ('BYLAW', '세칙'), ('RULE', '규칙'), ('ETC', '기타규정')], max_length=8, verbose_name='종류'),
        ),
    ]
