# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-10 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0005_auto_20180227_2314'),
        ('rule', '0005_auto_20180307_1448'),
    ]

    operations = [
    ]
