# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-13 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0006_merge_20180310_2159'),
        ('rule', '0006_merge_20180311_1702'),
    ]

    operations = [
    ]
